name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  echo "${{ secrets.CEYHUNMLOPS }}" | docker login -u "ceyhunmlops" --password-stdin && docker image build -t ceyhunmlops/mlops-flaskapp:v1 . && docker image push ceyhunmlops/mlops-flaskapp:v1

